// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.surgeryassist.core.entity;

import com.surgeryassist.core.entity.UserInfo;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserInfo_Roo_Configurable {
    
    declare @type: UserInfo: @Configurable;
    
}
